"""
JAZZ Trading United Nation - Core Data Models
Unified schemas for event packets, decision orders, execution records, and portfolio state.
"""

from dataclasses import dataclass, asdict, field
from typing import Optional, List, Dict, Any
import json
import time
import uuid


@dataclass
class EventPacket:
    """
    Unified, timestamped event packet output by Agent 1 (The Eyes).
    Format required: [timestamp, asset_id, spot_price, spot_change_velocity_60s, polymarket_best_bid, polymarket_best_ask, spread_bps]
    """
    timestamp: float
    asset_id: str
    spot_price: float
    spot_change_velocity_60s: float
    polymarket_best_bid: float
    polymarket_best_ask: float
    spread_bps: float
    
    # Metadata for execution & filtering
    secs_remaining: float = 0.0
    expiry_ts: float = 0.0
    top3_depth_usdc: float = 1200.0
    token_id: str = ""
    market_id: str = ""
    strike_price: float = 0.0
    realized_vol_60s: Optional[float] = None
    ofi: float = 0.0
    cross_venue_confirmed: bool = True

    def to_packet_list(self) -> list:
        """Returns the strictly required JSON event packet format."""
        return [
            self.timestamp,
            self.asset_id,
            round(self.spot_price, 4),
            round(self.spot_change_velocity_60s, 4),
            round(self.polymarket_best_bid, 4),
            round(self.polymarket_best_ask, 4),
            round(self.spread_bps, 2)
        ]

    def to_json(self) -> str:
        return json.dumps(self.to_packet_list())


@dataclass
class DecisionOrder:
    """
    Structured decision order generated by Agent 2 (The Brain).
    Format required: [signal_id, action="BUY", token_id, target_limit_price, calculated_edge_bps, max_size_shares]
    """
    signal_id: str
    token_id: str
    target_limit_price: float
    calculated_edge_bps: float
    max_size_shares: float
    action: str = "BUY"
    timestamp: float = field(default_factory=time.time)
    theoretical_probability: float = 0.0
    delta: float = 0.0
    asset_id: str = "BTC"

    def to_order_list(self) -> list:
        """Returns the strictly required JSON decision order format."""
        return [
            self.signal_id,
            self.action,
            self.token_id,
            round(self.target_limit_price, 4),
            round(self.calculated_edge_bps, 2),
            round(self.max_size_shares, 2)
        ]

    def to_json(self) -> str:
        return json.dumps(self.to_order_list())


@dataclass
class ExecutionRecord:
    """
    Record of order dispatch and on-chain / CLOB receipt by Agent 3 (The Hands).
    """
    client_order_id: str
    signal_id: str
    token_id: str
    side: str
    price: float
    size: float
    order_type: str
    submission_timestamp: float
    network_hash: str
    status: str  # "POSTED", "FILLED", "REJECTED", "CANCELLED"
    attempts: int = 1
    latency_ms: float = 0.0
    error: Optional[str] = None


@dataclass
class TradeRecord:
    """
    Position lifecycle record tracked by Agent 5 (The Ledger).
    """
    trade_id: str
    token_id: str
    entry_price: float
    shares: float
    entry_time: float
    exit_price: Optional[float] = None
    exit_time: Optional[float] = None
    duration_sec: float = 0.0
    slippage: float = 0.0
    net_pnl: float = 0.0
    status: str = "OPEN"  # "OPEN", "SETTLED"


@dataclass
class PortfolioMetrics:
    """
    Real-time performance analytics calculated by Agent 5 (The Ledger).
    """
    cash_balance_usdc: float
    total_trades: int
    win_rate: float
    profit_factor: float
    avg_execution_latency_ms: float
    max_drawdown_pct: float
    active_positions: int
    is_locked: bool = False
    lock_reason: Optional[str] = None
